# Builds the Json5.VisualStudio VSIX extension on Windows

name: build-vsix
on:
  workflow_dispatch:
    inputs:
      configuration:
        type: choice
        description: Configuration
        options:
        - Release
        - Debug
  push:
    branches: [ main, 'feature/*', 'rel/*' ]
    paths-ignore:
      - changelog.md
      - readme.md
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOTNET_NOLOGO: true
  PackOnBuild: true
  VersionPrefix: 42.42.${{ github.run_number }}
  VersionLabel: ${{ github.ref }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  MSBUILDTERMINALLOGGER: auto
  Configuration: ${{ github.event.inputs.configuration || 'Release' }}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: ⚙ dotnet
        uses: devlooped/actions-dotnet-env@v1

      - name: 🙏 build
        run: dotnet msbuild -r src/Json5.VisualStudio/Json5.VisualStudio.csproj -m:1 -bl:build.binlog

      - name: 🐛 logs
        uses: actions/upload-artifact@v4
        if: runner.debug && always()
        with:
          name: logs
          path: '*.binlog'
